networks:
- config:
    ipv4.address: 10.0.3.1/24
    ipv6.address: none
  description: ""
  name: lxdbr0
  type: ""
storage_pools:
- name: mnt-pool
  driver: dir
  config:
    source: "/mnt/lxd"
profiles:
- config: {}
  description: ""
  devices:
    eth0:
      name: eth0
      network: lxdbr0
      type: nic
  name: default
cluster: null
