---
- hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  become_user: root
  vars:
    PATH: /opt/sync-mirror
    HTML_PATH: "{{ PATH }}/html"

  tasks:
    - name: Installing packages
      apt:
        name: ['make', 'docker.io']
        state: present
        update_cache: True

    - name: Making {{ HTML_PATH }} dir
      file:
        path: "{{ HTML_PATH }}"
        state: directory
        owner: root
        group: root
        mode: 0755
        recurse: True

    - name: Coping files into {{ PATH }} dir
      template:
        src: templates/{{ item }}
        dest: "{{ PATH }}/{{ item }}"
      with_items:
        - Makefile
        - Dockerfile

    - name: Making cron entry
      cron:
        name: "sync-mirror"
        weekday: "6"
        minute: "45"
        hour: "3"
        user: root
        job: "make -f {{ PATH }}/Makefile sync && make -f {{ PATH }}/Dockerfile deploy"
        cron_file: /etc/crontab
        state: present