---
    - name: Installing package
      apt:
        name: ['docker.io']
        state: present

    - name: Copy client certs
      copy:
        src: "files{{ item }}"
        dest: "{{ item }}"
        owner: root
        group: root
        mode: 0400
      with_items:
        - /etc/docker/ca.pem
        - /etc/docker/client-cert.pem
        - /etc/docker/client-key.pem

